spring:
  datasource:
    url: jdbc:mysql://101.200.241.73:3306/mybatis?rewriteBatchedStatements=true
    username: root
    password: ZHAOBIN138
    #    type: com.zaxxer.hikari.HikariDataSource # 系统默认的数据源
    type: com.alibaba.druid.pool.DruidDataSource # 指定数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  executor-type: batch



#mybatis:
#  mapper-locations: com./*.xml # mapper文件所在文件夹
#  configuration: # 指定mybatis全局配置文件中的相关配置项
#    map-underscore-to-camel-case: true # 采用驼峰命名方式转换
